language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_0.49_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

script:
    - hugo

after_success: |
    if [ -n "$GITHUB_API_KEY" ]; then
    git checkout --orphan master
    git rm -rf .
    mv docs/* .
    rm -rf docs hugo_*
    git add -f --ignore-errors --all
    git -c user.name='Muhammad Usman' -c user.email='me@usmanmuhd.com' commit -m init
    git push -f -q https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$GITHUB_USER.github.io master
    fi
